### ISSUE TITLE
Agile Octopus Current/Next slot rates not updating since upgrading to v8.0.0

### ISSUE THREAD

**Issue by davidwalton0** [BottlecapDave/HomeAssistant-OctopusEnergy#353]
### Describe the bug

Immediately after upgrading to v8.0.0 at approx 15:18 on 05-August, the Agile Rates card showed only up to 22:30 slot, which was unusual, as it usually shows the next 24 hours. Both the 'Electricity Current Rate' and 'Electricity Next Slot Rate' appeared stuck at a value of '0.13'

Upon checking the Home Assistant dashboard this morning (06-August), I've now lost Rate data since the upgrade, and no Rates are shown in the Agile Rates card. The Electricity Current Rate and Electricity Next Slot Rate entities are shown as 'Unavailable':

<img width="515" alt="Screenshot 2023-08-06 103447" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/55101222/5fd5ba31-9bb3-49d7-ad9b-1c927e337062">

### Reproduction steps

No steps needed, the entities are unavailable.

### Expected behaviour

'Electricity Current Rate' and 'Electricity Next Slot Rate' entities should be available and report their respective data values

### Tariff Code

 E-1R-AGILE-FLEX-22-11-25-G

### Integration Version

v8.0.0

### Home Assistant Version

Home Assistant 2023.8.1 | Supervisor 2023.07.1 | Operating System 10.4 | Frontend 20230802.0 - latest

### Fresh Install?

Not specified

### Home Assistant Logs

Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/electricity/standing_charge.py:68
Integration: Sensor (documentation, issues)
First occurred: 5 August 2023 at 15:18:27 (2 occurrences)
Last logged: 10:08:43

octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/standing_charge.py", line 68, in async_update
    standard_charge_result = self.coordinator.data[self._mpan] if self.coordinator.data is not None and self._mpan in self.coordinator.data else None
                                                                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/electricity/current_accumulative_consumption.py:89
Integration: Sensor (documentation, issues)
First occurred: 5 August 2023 at 15:18:27 (2 occurrences)
Last logged: 10:08:43

octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/current_accumulative_consumption.py", line 89, in async_update
    standing_charge = self._standing_charge_coordinator.data[self._mpan]["value_inc_vat"] if self._standing_charge_coordinator.data is not None and self._mpan in self._standing_charge_coordinator.data and "value_inc_vat" in self._standing_charge_coordinator.data[self._mpan] else None
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/electricity/current_accumulative_consumption_peak.py:100
Integration: Sensor (documentation, issues)
First occurred: 5 August 2023 at 15:18:27 (2 occurrences)
Last logged: 10:08:43

octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/current_accumulative_consumption_peak.py", line 100, in async_update
    standing_charge = self._standing_charge_coordinator.data[self._mpan]["value_inc_vat"] if self._standing_charge_coordinator.data is not None and self._mpan in self._standing_charge_coordinator.data and "value_inc_vat" in self._standing_charge_coordinator.data[self._mpan] else None
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/electricity/current_accumulative_consumption_off_peak.py:100
Integration: Sensor (documentation, issues)
First occurred: 5 August 2023 at 15:18:28 (2 occurrences)
Last logged: 10:08:43

octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/current_accumulative_consumption_off_peak.py", line 100, in async_update
    standing_charge = self._standing_charge_coordinator.data[self._mpan]["value_inc_vat"] if self._standing_charge_coordinator.data is not None and self._mpan in self._standing_charge_coordinator.data and "value_inc_vat" in self._standing_charge_coordinator.data[self._mpan] else None
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/electricity/current_accumulative_cost.py:99
Integration: Sensor (documentation, issues)
First occurred: 5 August 2023 at 15:18:28 (2 occurrences)
Last logged: 10:08:43

octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/current_accumulative_cost.py", line 99, in async_update
    standing_charge = self._standing_charge_coordinator.data[self._mpan]["value_inc_vat"] if self._standing_charge_coordinator.data is not None and self._mpan in self._standing_charge_coordinator.data and "value_inc_vat" in self._standing_charge_coordinator.data[self._mpan] else None
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/electricity/current_accumulative_cost_peak.py:96
Integration: Sensor (documentation, issues)
First occurred: 5 August 2023 at 15:18:28 (2 occurrences)
Last logged: 10:08:43

octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/current_accumulative_cost_peak.py", line 96, in async_update
    standing_charge = self._standing_charge_coordinator.data[self._mpan]["value_inc_vat"] if self._standing_charge_coordinator.data is not None and self._mpan in self._standing_charge_coordinator.data and "value_inc_vat" in self._standing_charge_coordinator.data[self._mpan] else None
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/electricity/current_accumulative_cost_off_peak.py:96
Integration: Sensor (documentation, issues)
First occurred: 5 August 2023 at 15:18:28 (2 occurrences)
Last logged: 10:08:43

octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/current_accumulative_cost_off_peak.py", line 96, in async_update
    standing_charge = self._standing_charge_coordinator.data[self._mpan]["value_inc_vat"] if self._standing_charge_coordinator.data is not None and self._mpan in self._standing_charge_coordinator.data and "value_inc_vat" in self._standing_charge_coordinator.data[self._mpan] else None
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by BottlecapDave** [comment]
Hi and sorry that you're having issues. I'm not sure why you're getting all of those errors in your logs. I saw it once and can never recreate the issue. I've switched my instance to your tariff and i'm able to see the information. 

Do you have anything stored in your `all_rates` attribute of your current rate sensor?
Have you tried reloading the integration or restarting your HA instance?

**Comment by davidwalton0** [comment]
Thanks for the quick response.

**Did you enable any new sensors?**
No, no changes at all - just upgraded. Prior to the upgrade, all worked OK

**Do you have anything stored in your all_rates attribute of your current rate sensor?**
Nothing stored in the all_rates attribute:
<img width="368" alt="Screenshot 2023-08-06 120908" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/55101222/d17f04e2-711f-4c10-92ba-db73697305c7">

**Have you tried reloading the integration or restarting your HA instance?**
Reloaded the integration several times, refreshed the browser (a Chrome instance displaying the HA dashboard) several times.
But I haven't restarted HA since it was restarted after upgrading the integration to v8.0.0, just just tried that. And...
It works! Values are back & working as expected. The Agile Rates card has returned as it should and if I check the all-rates attribute, a full list of values are shown. Issue fixed!

Thanks for the help 
I should have tried that tbh, but it may have cleared some valuable clue and made things worse.

**Comment by BottlecapDave** [comment]
I'll continue investigating the issue and see if anything jumps out as if it happens to you, then it'll probably happen to someone else.

**Comment by BottlecapDave** [comment]
A future update should make what you're seeing more stable as I've moved a lot of logic out of the update loop and into the state property. I'm following HA developer docs for this sensor (and the sensor you've posted is a very simple one), so not sure if they've changed something in the latest release to make this less stable.
