### ISSUE TITLE
Error in the logs after upgrading to 10.1.3 (10.1.2 all good) 

### ISSUE THREAD

**Issue by dnedeltchev** [BottlecapDave/HomeAssistant-OctopusEnergy#775]
### Describe the bug

Logger: homeassistant.setup
Source: setup.py:404
First occurred: 17:07:04 (1 occurrences)
Last logged: 17:07:04

Unable to prepare setup for platform 'octopus_energy.binary_sensor': Platform not found (cannot import name 'get_dispatch_times' from 'custom_components.octopus_energy.intelligent' (/config/custom_components/octopus_energy/intelligent/__init__.py)).

### Reproduction steps

Upgrade to 10.1.3 and look in the logs

### Expected behaviour

No errors in logs

### Tariff Code

0.293811 GBP/kWh electricity and 0.074477 GBP/kWh gas

### Integration Version

10.1.3

### Home Assistant Version

2024.2.2

### Fresh Install?

After upgrading

### Home Assistant Logs

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:576
Integration: Sensor (documentation, issues)
First occurred: 17:10:04 (2 occurrences)
Last logged: 17:10:04

Entity sensor.electric_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/HandyHat/ha-hildebrandglow-dcc/issues
Entity sensor.gas_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/HandyHat/ha-hildebrandglow-dcc/issues
Logger: homeassistant.setup
Source: setup.py:404
First occurred: 17:10:03 (1 occurrences)
Last logged: 17:10:03

Unable to prepare setup for platform 'octopus_energy.binary_sensor': Platform not found (cannot import name 'get_dispatch_times' from 'custom_components.octopus_energy.intelligent' (/config/custom_components/octopus_energy/intelligent/__init__.py)).

Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 17:09:52 (16 occurrences)
Last logged: 17:15:43

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Sorry. Can you try 10.1.4 please?

**Comment by dnedeltchev** [comment]
No errors with  .4
👍
