### ISSUE TITLE
Heat pump no longer shown from 16.2.0

### ISSUE THREAD

**Issue by johncuthbertuk** [BottlecapDave/HomeAssistant-OctopusEnergy#1464]
### Describe the bug

Upgrading from 16.1.0 to 16.2.0 onwards the heat pump devices all show unavailable. I tried deleting the account and re-adding it but all the heat pump devices doesn't appear, only the electricity meters. Re-installing 16.1.0 brings them all back.

### Reproduction steps

Upgrade from 16.1.0 to 16.2.0

### Expected behaviour

Upgrading to 16.2.0 onwards shouldn't affect the heat pump devices

### Tariff Code

N/A

### Integration Version

16.2.0

### Home Assistant Version

2024.11.3

### Fresh Install?

After upgrading

### Home Assistant Logs

```
"Failed to retrieve - type object 'HeatPumpResponse' has no attribute 'model_validate'"
```

### Confirmation

- [x] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [x] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by johncuthbertuk** [comment]
Updated original post as found an error which might help pinpoint the underlying issue as the `HeatPumpResponse` object doesn't seem to match for one of the attributes

**Comment by johncuthbertuk** [comment]
Digging further into this, I think the issue is the minimum version of HA now supported, possibly 2024.12 based on the following: https://www.home-assistant.io/blog/2024/12/04/release-202412/#weve-upgraded-to-python-313

**Comment by johncuthbertuk** [comment]
Upgraded HA to `2024.12` - still failed

Upgraded HA `2025.1` - now works with `16.2.0`

TL;DR minimum version required needs bumped up to `2025.1`

**Comment by BottlecapDave** [comment]
Hello and sorry for encountering this issue. This was missed when an external contribution was made to fix the raised warning. I've approved the pull request. I'll update the change log notes on the effected versions but I unfortunately can't fix the hacs logic for those releases. This will be rectified as part of the next release.
