### ISSUE TITLE
Sensors including binary_sensor.octopus_energy_a_xxxxxxx_intelligent_dispatching reporting unavailable after upgrade to 14.0.1

### ISSUE THREAD

**Issue by RGx01** [BottlecapDave/HomeAssistant-OctopusEnergy#1224]
### Describe the bug

Not sure if I upgraded at a point where the API is down? Tried rolling back to 14.0.0 but I have the same issue.

17 sensors are reporting unavailable:
binary_sensor.octopus_energy_a_xxxxxxx_intelligent_dispatching 
sensor.octopus_energy_a_xxxxxx_intelligent_state
+15 others 

<img width="620" alt="Image" src="https://github.com/user-attachments/assets/9e9bc988-a20b-4612-b251-f8f909f7e123" />

### Reproduction steps

upgrade to 14.0.1

### Expected behaviour

sensors are available

### Tariff Code

NA

### Integration Version

14.0.1

### Home Assistant Version

Core 2025.2.4 Supervisor 2025.02.1 Operating System 14.2 Frontend 20250214.0

### Fresh Install?

After upgrading

### Home Assistant Logs

2025-02-18 06:46:38.759 ERROR (MainThread) [custom_components.octopus_energy.coordinators.previous_consumption_and_rates] Unexpected error fetching xxxxxx_previous_consumption_and_rates data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/previous_consumption_and_rates.py", line 451, in async_update_data
    dispatches.dispatches if dispatches is not None else None,
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IntelligentDispatches' object has no attribute 'dispatches'

2025-02-18 06:47:08.926 ERROR (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Unexpected error fetching intelligent_dispatches-xxxxxx data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 56, in __automatic_refresh_dispatches
    return await self.__refresh_dispatches()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 215, in async_update_intelligent_dispatches_data
    hass.data[DOMAIN][account_id][DATA_INTELLIGENT_DISPATCHES] = await async_refresh_intelligent_dispatches(
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 110, in async_refresh_intelligent_dispatches
    requests_current_hour = existing_intelligent_dispatches_result.requests_current_hour if existing_intelligent_dispatches_result is not None else 0
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IntelligentDispatches' object has no attribute 'requests_current_hour'

### Confirmation

- [x] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [x] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by bobbinz** [comment]
I upgraded at 23:30 last night had had the same issue and wondered the same about the API being down.

Given this is two different times I suspect it is a real bug.

**Comment by RGx01** [comment]
I'm back up and running, think I was unlucky to upgrade at the time the API was down??

**Comment by bristolbaz** [comment]
this is still broken for me after rolling back and then upgrading to 14.0.1
works fine on 14.0.0 - IO sensors are showing as unavailable

**Comment by fourmonks** [comment]
Same issue. @RGx01 what did you do to fix it?

**Comment by bobbinz** [comment]
I just went to HACS and redownloaded 14.0.0. Restart and ignore update.

**Comment by RGx01** [comment]
> Is a full rollback required? How do I rollback just HomeAssistant-OctopusEnergy?

go into HACS find the Octopus Energy Integration > click the three dots in top right and redownload, select the version required (14.0.0) 

<img width="1422" alt="Image" src="https://github.com/user-attachments/assets/54eb03e7-ecde-49ce-9a71-4e6fc65345b7" />

**Comment by fourmonks** [comment]
> > Is a full rollback required? How do I rollback just HomeAssistant-OctopusEnergy?
> 
> go into HACS find the Octopus Energy Integration > click the three dots in top right and redownload, select the version required (14.0.0)
> 
> <img alt="Image" width="1422" src="https://private-user-images.githubusercontent.com/149301136/414152472-54eb03e7-ecde-49ce-9a71-4e6fc65345b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk4NjY0OTAsIm5iZiI6MTczOTg2NjE5MCwicGF0aCI6Ii8xNDkzMDExMzYvNDE0MTUyNDcyLTU0ZWIwM2U3LWVjZGUtNDljZS05YTcxLTRlNmZjNjUzNDViNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxOFQwODA5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzUzM2Y2ZTQzYzllNzMwNTI3N2VmNWI4N2I1OTc4MGFjYzdkMzU2OGI2Y2UwZDQ4NTA5NjhjMjg1NWQ5OGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kU5uh9Sq1MnTz7pAIFDVmyWl_79fIS_L_-QJhFXrwX4">

tvm - seems ok again on 14.0.0

**Comment by neildsb** [comment]
see https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/1223

**Comment by bobbinz** [comment]
> see [#1223](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/1223)

I'm on automatic and have the issue

**Comment by timstephenson20** [comment]
Same here on 14.0.1; reverted to 14.0.0 and seems to be working again after a restart.

**Comment by neildsb** [comment]
from 14.0.2 -

This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.intelligent_dispatches
Source: helpers/update_coordinator.py:380
integration: Octopus Energy (documentation, issues)
First occurred: 3:08:08 pm (2 occurrences)
Last logged: 3:09:08 pm

Unexpected error fetching intelligent_dispatches-A-xxxxxxx data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 56, in __automatic_refresh_dispatches
    return await self.__refresh_dispatches()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 215, in async_update_intelligent_dispatches_data
    hass.data[DOMAIN][account_id][DATA_INTELLIGENT_DISPATCHES] = await async_refresh_intelligent_dispatches(
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 174, in async_refresh_intelligent_dispatches
    existing_intelligent_dispatches_result.dispatches.planned[0].start != dispatches.planned[0].start or
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by johnwb87** [comment]
Very similar error immediately on restart from 15.0.2.

```Logger: homeassistant.config_entries
Source: config_entries.py:637
First occurred: 15:07:57 (2 occurrences)
Last logged: 16:06:35

Error setting up entry A-xxxxxxxx for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 637, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 155, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 468, in async_setup_dependencies
    if hass.data[DOMAIN][account_id][DATA_INTELLIGENT_DISPATCHES] is None:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'INTELLIGENT_DISPATCHES'
```

**Comment by BottlecapDave** [comment]
Hello and sorry you've all encountered this issue. It should be fixed as part of [v14.0.3](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v14.0.3).

**Comment by neildsb** [comment]
No need to apologise, thanks for your help and effort

**Comment by mozster** [comment]
Hi @BottlecapDave not sure if I should raise a new issue, but I'm seeing similar problems with v14.0.3:

1) the intelligent_dispatching entity's array of planned and completed events isn't getting populated:

![Image](https://github.com/user-attachments/assets/3b72db8c-0280-4e74-b6de-09d1149e0ed1)

2) the intelligent_state entity is always showing as unknown

Is there any specific debug I should generate or config settings I should check?

**Comment by BottlecapDave** [comment]
Please raise a new issue along with any errors found in your HA logs and diagnostic information as per the faq.
